name: Deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
    
      - name: Install dependencies
        run: npm install
    
      - name: Build project
        run: npm run build

      - name: Verify build output
        run: ls -la ./build

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app
          path: build
    
      - name: Deploy to GitHub Pages
        id: deploy-to-github-pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: app

      - name: Log deployment URL
        run: echo "Deployed to GitHub Pages at ${{ steps.deploy-to-github-pages.outputs.page_url }}"